#!/bin/env Rscript

require( ant ) 

# copy all files from the testng directory into the current directory
testng.dir <- system.file("testng", package = "RemoteREngine.test")
files <- list.files( testng.dir, full.names = TRUE )
for( f in files){
	file.copy( f, basename(f) )
}

# run them with ant
ant( arguments = "runtests" )

